 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "COST", -f 175
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "AAPL", -f 1313
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "TSLA", -f 2100
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "FUTU", -f 1143
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "SBUX", -f 45
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "HD", -f 332
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "CMG", -f 2112
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "LLY", -f 1015
 ts-node src/client/main_create_user_portfolio.ts -i 7 -u sameer -n "Sameer Kulkarni" -e sameer@buybak.xyz -p 6306967660 -a "1 infinite loop, Naperville, IL" -s "XOM", -f 75
